//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bigdesk8.Business.DebugManager {
    
    
    public partial class View {
        
        /// <summary>
        /// DBText13 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Bigdesk8.Web.Controls.DBText DBText13;
        
        /// <summary>
        /// DBText14 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Bigdesk8.Web.Controls.DBText DBText14;
        
        /// <summary>
        /// tb_xmmc 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Bigdesk8.Web.Controls.DBText tb_xmmc;
        
        /// <summary>
        /// tb_jsdw 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Bigdesk8.Web.Controls.DBText tb_jsdw;
        
        /// <summary>
        /// DBText10 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Bigdesk8.Web.Controls.DBText DBText10;
        
        /// <summary>
        /// DBMemoBox1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Bigdesk8.Web.Controls.DBMemo DBMemoBox1;
    }
}
