//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WxjzgcjczyTimerService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://58.213.147.243:8080/jscedc/services/dataDownService.dataDownServiceHttpSoa" +
            "p11Endpoint/")]
        public string WxjzgcjczyTimerService3_0_DataDownService_dataDownService {
            get {
                return ((string)(this["WxjzgcjczyTimerService3_0_DataDownService_dataDownService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://221.226.0.185/AppSgtSjsc/WebServiceStxm.asmx")]
        public string WxjzgcjczyTimerService3_0_WebServiceStxm_WebServiceStxm {
            get {
                return ((string)(this["WxjzgcjczyTimerService3_0_WebServiceStxm_WebServiceStxm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://58.213.147.243:8080/jscedc/services/NewDataService.NewDataServiceHttpSoap1" +
            "1Endpoint/")]
        public string WxjzgcjczyTimerService3_0_NewDataService_NewDataService {
            get {
                return ((string)(this["WxjzgcjczyTimerService3_0_NewDataService_NewDataService"]));
            }
        }
    }
}
