//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8009
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wxjzgcjczy.BLL.ReceiveDataServiceSpace {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType2anyTypeMap", Namespace="http://Server.WebService", ItemName="anyType2anyTypeMap")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType2anyTypeMap : System.Collections.Generic.List<Wxjzgcjczy.BLL.ReceiveDataServiceSpace.anyType2anyTypeMap> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="anyType2anyTypeMap", Namespace="http://Server.WebService", ItemName="entry")]
    [System.SerializableAttribute()]
    public class anyType2anyTypeMap : System.Collections.Generic.List<Wxjzgcjczy.BLL.ReceiveDataServiceSpace.entry> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entry", Namespace="http://Server.WebService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wxjzgcjczy.BLL.ReceiveDataServiceSpace.ArrayOfAnyType2anyTypeMap))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wxjzgcjczy.BLL.ReceiveDataServiceSpace.anyType2anyTypeMap))]
    public partial class entry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Server.WebService", ConfigurationName="ReceiveDataServiceSpace.ReceiveDataServicePortType")]
    public interface ReceiveDataServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getGdxyf(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string TBContractRecordManage(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string GetDataFromSxypt(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getXyptPjf(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        Wxjzgcjczy.BLL.ReceiveDataServiceSpace.ArrayOfAnyType2anyTypeMap SendBegin(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string ReceiveData(Wxjzgcjczy.BLL.ReceiveDataServiceSpace.ArrayOfAnyType2anyTypeMap in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        byte[] SnapFileByInternet(string in0, string in1, string in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getXyptRs(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string TjRetrieveByUpdate(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string XyInnerptPjf(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string TBProjectInfoTime(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string RetrieveData(string in0, string in1, string in2, string in3, string in4, string in5, string in6);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string TBContractRecordManageTime(string in0, string in1, string in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string SnapDataByInternet(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string Huoqu(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string SaveTBDataToSt(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string HTBA(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getXyptPjfmx(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string saveZcjzs(string in0, string in1, byte[] in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string TBProjectInfo(string in0, string in1, string in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getQsXyptPjf(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string TjxtFromXmData(string in0, string in1, string in2, string in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string SaveDataToSt(string in0, string in1, string in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string SaveStData(string in0, string in1, string in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string TjxtFromQyData(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string ToCityPlatform(string in0, string in1, string in2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ReceiveDataServicePortTypeChannel : Wxjzgcjczy.BLL.ReceiveDataServiceSpace.ReceiveDataServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ReceiveDataServicePortTypeClient : System.ServiceModel.ClientBase<Wxjzgcjczy.BLL.ReceiveDataServiceSpace.ReceiveDataServicePortType>, Wxjzgcjczy.BLL.ReceiveDataServiceSpace.ReceiveDataServicePortType {
        
        public ReceiveDataServicePortTypeClient() {
        }
        
        public ReceiveDataServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiveDataServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveDataServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveDataServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getGdxyf(string in0, string in1, string in2) {
            return base.Channel.getGdxyf(in0, in1, in2);
        }
        
        public string TBContractRecordManage(string in0, string in1, string in2, string in3) {
            return base.Channel.TBContractRecordManage(in0, in1, in2, in3);
        }
        
        public string GetDataFromSxypt(string in0, string in1, string in2, string in3) {
            return base.Channel.GetDataFromSxypt(in0, in1, in2, in3);
        }
        
        public string getXyptPjf(string in0) {
            return base.Channel.getXyptPjf(in0);
        }
        
        public Wxjzgcjczy.BLL.ReceiveDataServiceSpace.ArrayOfAnyType2anyTypeMap SendBegin(string in0) {
            return base.Channel.SendBegin(in0);
        }
        
        public string ReceiveData(Wxjzgcjczy.BLL.ReceiveDataServiceSpace.ArrayOfAnyType2anyTypeMap in0, string in1) {
            return base.Channel.ReceiveData(in0, in1);
        }
        
        public byte[] SnapFileByInternet(string in0, string in1, string in2, string in3, string in4) {
            return base.Channel.SnapFileByInternet(in0, in1, in2, in3, in4);
        }
        
        public string getXyptRs(string in0, string in1) {
            return base.Channel.getXyptRs(in0, in1);
        }
        
        public string TjRetrieveByUpdate(string in0, string in1) {
            return base.Channel.TjRetrieveByUpdate(in0, in1);
        }
        
        public string XyInnerptPjf(string in0, string in1, string in2) {
            return base.Channel.XyInnerptPjf(in0, in1, in2);
        }
        
        public string TBProjectInfoTime(string in0, string in1, string in2, string in3) {
            return base.Channel.TBProjectInfoTime(in0, in1, in2, in3);
        }
        
        public string RetrieveData(string in0, string in1, string in2, string in3, string in4, string in5, string in6) {
            return base.Channel.RetrieveData(in0, in1, in2, in3, in4, in5, in6);
        }
        
        public string TBContractRecordManageTime(string in0, string in1, string in2, string in3, string in4) {
            return base.Channel.TBContractRecordManageTime(in0, in1, in2, in3, in4);
        }
        
        public string SnapDataByInternet(string in0, string in1, string in2, string in3) {
            return base.Channel.SnapDataByInternet(in0, in1, in2, in3);
        }
        
        public string Huoqu(string in0) {
            return base.Channel.Huoqu(in0);
        }
        
        public string SaveTBDataToSt(string in0, string in1, string in2, string in3) {
            return base.Channel.SaveTBDataToSt(in0, in1, in2, in3);
        }
        
        public string HTBA(string in0, string in1, string in2) {
            return base.Channel.HTBA(in0, in1, in2);
        }
        
        public string getXyptPjfmx(string in0, string in1, string in2) {
            return base.Channel.getXyptPjfmx(in0, in1, in2);
        }
        
        public string saveZcjzs(string in0, string in1, byte[] in2, string in3, string in4, string in5) {
            return base.Channel.saveZcjzs(in0, in1, in2, in3, in4, in5);
        }
        
        public string TBProjectInfo(string in0, string in1, string in2, string in3, string in4) {
            return base.Channel.TBProjectInfo(in0, in1, in2, in3, in4);
        }
        
        public string getQsXyptPjf(string in0, string in1, string in2) {
            return base.Channel.getQsXyptPjf(in0, in1, in2);
        }
        
        public string TjxtFromXmData(string in0, string in1, string in2, string in3) {
            return base.Channel.TjxtFromXmData(in0, in1, in2, in3);
        }
        
        public string SaveDataToSt(string in0, string in1, string in2, string in3, string in4) {
            return base.Channel.SaveDataToSt(in0, in1, in2, in3, in4);
        }
        
        public string SaveStData(string in0, string in1, string in2, string in3, string in4) {
            return base.Channel.SaveStData(in0, in1, in2, in3, in4);
        }
        
        public string TjxtFromQyData(string in0, string in1, string in2) {
            return base.Channel.TjxtFromQyData(in0, in1, in2);
        }
        
        public string ToCityPlatform(string in0, string in1, string in2) {
            return base.Channel.ToCityPlatform(in0, in1, in2);
        }
    }
}
