//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8009
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.8009 版自动生成。
// 
#pragma warning disable 1591

namespace Wxjzgcjczy.Web.ReceiveDataService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReceiveDataServiceHttpBinding", Namespace="http://Server.WebService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(anyType2anyTypeMapEntry[][]))]
    public partial class ReceiveDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getGdxyfOperationCompleted;
        
        private System.Threading.SendOrPostCallback TBContractRecordManageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataFromSxyptOperationCompleted;
        
        private System.Threading.SendOrPostCallback getXyptPjfOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBeginOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SnapFileByInternetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getXyptRsOperationCompleted;
        
        private System.Threading.SendOrPostCallback TjRetrieveByUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback XyInnerptPjfOperationCompleted;
        
        private System.Threading.SendOrPostCallback TBProjectInfoTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback TBContractRecordManageTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SnapDataByInternetOperationCompleted;
        
        private System.Threading.SendOrPostCallback HuoquOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveTBDataToStOperationCompleted;
        
        private System.Threading.SendOrPostCallback HTBAOperationCompleted;
        
        private System.Threading.SendOrPostCallback getXyptPjfmxOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveZcjzsOperationCompleted;
        
        private System.Threading.SendOrPostCallback TBProjectInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getQsXyptPjfOperationCompleted;
        
        private System.Threading.SendOrPostCallback TjxtFromXmDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveDataToStOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveStDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback TjxtFromQyDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ToCityPlatformOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReceiveDataService() {
            this.Url = global::Wxjzgcjczy.Web.Properties.Settings.Default.Wxjzgcjczy_Web_ReceiveDataService_ReceiveDataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getGdxyfCompletedEventHandler getGdxyfCompleted;
        
        /// <remarks/>
        public event TBContractRecordManageCompletedEventHandler TBContractRecordManageCompleted;
        
        /// <remarks/>
        public event GetDataFromSxyptCompletedEventHandler GetDataFromSxyptCompleted;
        
        /// <remarks/>
        public event getXyptPjfCompletedEventHandler getXyptPjfCompleted;
        
        /// <remarks/>
        public event SendBeginCompletedEventHandler SendBeginCompleted;
        
        /// <remarks/>
        public event ReceiveDataCompletedEventHandler ReceiveDataCompleted;
        
        /// <remarks/>
        public event SnapFileByInternetCompletedEventHandler SnapFileByInternetCompleted;
        
        /// <remarks/>
        public event getXyptRsCompletedEventHandler getXyptRsCompleted;
        
        /// <remarks/>
        public event TjRetrieveByUpdateCompletedEventHandler TjRetrieveByUpdateCompleted;
        
        /// <remarks/>
        public event XyInnerptPjfCompletedEventHandler XyInnerptPjfCompleted;
        
        /// <remarks/>
        public event TBProjectInfoTimeCompletedEventHandler TBProjectInfoTimeCompleted;
        
        /// <remarks/>
        public event RetrieveDataCompletedEventHandler RetrieveDataCompleted;
        
        /// <remarks/>
        public event TBContractRecordManageTimeCompletedEventHandler TBContractRecordManageTimeCompleted;
        
        /// <remarks/>
        public event SnapDataByInternetCompletedEventHandler SnapDataByInternetCompleted;
        
        /// <remarks/>
        public event HuoquCompletedEventHandler HuoquCompleted;
        
        /// <remarks/>
        public event SaveTBDataToStCompletedEventHandler SaveTBDataToStCompleted;
        
        /// <remarks/>
        public event HTBACompletedEventHandler HTBACompleted;
        
        /// <remarks/>
        public event getXyptPjfmxCompletedEventHandler getXyptPjfmxCompleted;
        
        /// <remarks/>
        public event saveZcjzsCompletedEventHandler saveZcjzsCompleted;
        
        /// <remarks/>
        public event TBProjectInfoCompletedEventHandler TBProjectInfoCompleted;
        
        /// <remarks/>
        public event getQsXyptPjfCompletedEventHandler getQsXyptPjfCompleted;
        
        /// <remarks/>
        public event TjxtFromXmDataCompletedEventHandler TjxtFromXmDataCompleted;
        
        /// <remarks/>
        public event SaveDataToStCompletedEventHandler SaveDataToStCompleted;
        
        /// <remarks/>
        public event SaveStDataCompletedEventHandler SaveStDataCompleted;
        
        /// <remarks/>
        public event TjxtFromQyDataCompletedEventHandler TjxtFromQyDataCompleted;
        
        /// <remarks/>
        public event ToCityPlatformCompletedEventHandler ToCityPlatformCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getGdxyf([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("getGdxyf", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getGdxyfAsync(string in0, string in1, string in2) {
            this.getGdxyfAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void getGdxyfAsync(string in0, string in1, string in2, object userState) {
            if ((this.getGdxyfOperationCompleted == null)) {
                this.getGdxyfOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGdxyfOperationCompleted);
            }
            this.InvokeAsync("getGdxyf", new object[] {
                        in0,
                        in1,
                        in2}, this.getGdxyfOperationCompleted, userState);
        }
        
        private void OngetGdxyfOperationCompleted(object arg) {
            if ((this.getGdxyfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGdxyfCompleted(this, new getGdxyfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string TBContractRecordManage([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("TBContractRecordManage", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TBContractRecordManageAsync(string in0, string in1, string in2, string in3) {
            this.TBContractRecordManageAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void TBContractRecordManageAsync(string in0, string in1, string in2, string in3, object userState) {
            if ((this.TBContractRecordManageOperationCompleted == null)) {
                this.TBContractRecordManageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTBContractRecordManageOperationCompleted);
            }
            this.InvokeAsync("TBContractRecordManage", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.TBContractRecordManageOperationCompleted, userState);
        }
        
        private void OnTBContractRecordManageOperationCompleted(object arg) {
            if ((this.TBContractRecordManageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TBContractRecordManageCompleted(this, new TBContractRecordManageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string GetDataFromSxypt([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("GetDataFromSxypt", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataFromSxyptAsync(string in0, string in1, string in2, string in3) {
            this.GetDataFromSxyptAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void GetDataFromSxyptAsync(string in0, string in1, string in2, string in3, object userState) {
            if ((this.GetDataFromSxyptOperationCompleted == null)) {
                this.GetDataFromSxyptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataFromSxyptOperationCompleted);
            }
            this.InvokeAsync("GetDataFromSxypt", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.GetDataFromSxyptOperationCompleted, userState);
        }
        
        private void OnGetDataFromSxyptOperationCompleted(object arg) {
            if ((this.GetDataFromSxyptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataFromSxyptCompleted(this, new GetDataFromSxyptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getXyptPjf([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getXyptPjf", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getXyptPjfAsync(string in0) {
            this.getXyptPjfAsync(in0, null);
        }
        
        /// <remarks/>
        public void getXyptPjfAsync(string in0, object userState) {
            if ((this.getXyptPjfOperationCompleted == null)) {
                this.getXyptPjfOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXyptPjfOperationCompleted);
            }
            this.InvokeAsync("getXyptPjf", new object[] {
                        in0}, this.getXyptPjfOperationCompleted, userState);
        }
        
        private void OngetXyptPjfOperationCompleted(object arg) {
            if ((this.getXyptPjfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXyptPjfCompleted(this, new getXyptPjfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("out", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("anyType2anyTypeMap")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false, NestingLevel=1)]
        public anyType2anyTypeMapEntry[][] SendBegin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("SendBegin", new object[] {
                        in0});
            return ((anyType2anyTypeMapEntry[][])(results[0]));
        }
        
        /// <remarks/>
        public void SendBeginAsync(string in0) {
            this.SendBeginAsync(in0, null);
        }
        
        /// <remarks/>
        public void SendBeginAsync(string in0, object userState) {
            if ((this.SendBeginOperationCompleted == null)) {
                this.SendBeginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBeginOperationCompleted);
            }
            this.InvokeAsync("SendBegin", new object[] {
                        in0}, this.SendBeginOperationCompleted, userState);
        }
        
        private void OnSendBeginOperationCompleted(object arg) {
            if ((this.SendBeginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBeginCompleted(this, new SendBeginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string ReceiveData([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("anyType2anyTypeMap")] [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false, NestingLevel=1)] anyType2anyTypeMapEntry[][] in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
            object[] results = this.Invoke("ReceiveData", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveDataAsync(anyType2anyTypeMapEntry[][] in0, string in1) {
            this.ReceiveDataAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void ReceiveDataAsync(anyType2anyTypeMapEntry[][] in0, string in1, object userState) {
            if ((this.ReceiveDataOperationCompleted == null)) {
                this.ReceiveDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveDataOperationCompleted);
            }
            this.InvokeAsync("ReceiveData", new object[] {
                        in0,
                        in1}, this.ReceiveDataOperationCompleted, userState);
        }
        
        private void OnReceiveDataOperationCompleted(object arg) {
            if ((this.ReceiveDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveDataCompleted(this, new ReceiveDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", DataType="base64Binary", IsNullable=true)]
        public byte[] SnapFileByInternet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4) {
            object[] results = this.Invoke("SnapFileByInternet", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void SnapFileByInternetAsync(string in0, string in1, string in2, string in3, string in4) {
            this.SnapFileByInternetAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void SnapFileByInternetAsync(string in0, string in1, string in2, string in3, string in4, object userState) {
            if ((this.SnapFileByInternetOperationCompleted == null)) {
                this.SnapFileByInternetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSnapFileByInternetOperationCompleted);
            }
            this.InvokeAsync("SnapFileByInternet", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.SnapFileByInternetOperationCompleted, userState);
        }
        
        private void OnSnapFileByInternetOperationCompleted(object arg) {
            if ((this.SnapFileByInternetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SnapFileByInternetCompleted(this, new SnapFileByInternetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getXyptRs([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
            object[] results = this.Invoke("getXyptRs", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getXyptRsAsync(string in0, string in1) {
            this.getXyptRsAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getXyptRsAsync(string in0, string in1, object userState) {
            if ((this.getXyptRsOperationCompleted == null)) {
                this.getXyptRsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXyptRsOperationCompleted);
            }
            this.InvokeAsync("getXyptRs", new object[] {
                        in0,
                        in1}, this.getXyptRsOperationCompleted, userState);
        }
        
        private void OngetXyptRsOperationCompleted(object arg) {
            if ((this.getXyptRsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXyptRsCompleted(this, new getXyptRsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string TjRetrieveByUpdate([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
            object[] results = this.Invoke("TjRetrieveByUpdate", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TjRetrieveByUpdateAsync(string in0, string in1) {
            this.TjRetrieveByUpdateAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void TjRetrieveByUpdateAsync(string in0, string in1, object userState) {
            if ((this.TjRetrieveByUpdateOperationCompleted == null)) {
                this.TjRetrieveByUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTjRetrieveByUpdateOperationCompleted);
            }
            this.InvokeAsync("TjRetrieveByUpdate", new object[] {
                        in0,
                        in1}, this.TjRetrieveByUpdateOperationCompleted, userState);
        }
        
        private void OnTjRetrieveByUpdateOperationCompleted(object arg) {
            if ((this.TjRetrieveByUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TjRetrieveByUpdateCompleted(this, new TjRetrieveByUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string XyInnerptPjf([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("XyInnerptPjf", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XyInnerptPjfAsync(string in0, string in1, string in2) {
            this.XyInnerptPjfAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void XyInnerptPjfAsync(string in0, string in1, string in2, object userState) {
            if ((this.XyInnerptPjfOperationCompleted == null)) {
                this.XyInnerptPjfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXyInnerptPjfOperationCompleted);
            }
            this.InvokeAsync("XyInnerptPjf", new object[] {
                        in0,
                        in1,
                        in2}, this.XyInnerptPjfOperationCompleted, userState);
        }
        
        private void OnXyInnerptPjfOperationCompleted(object arg) {
            if ((this.XyInnerptPjfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XyInnerptPjfCompleted(this, new XyInnerptPjfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string TBProjectInfoTime([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("TBProjectInfoTime", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TBProjectInfoTimeAsync(string in0, string in1, string in2, string in3) {
            this.TBProjectInfoTimeAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void TBProjectInfoTimeAsync(string in0, string in1, string in2, string in3, object userState) {
            if ((this.TBProjectInfoTimeOperationCompleted == null)) {
                this.TBProjectInfoTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTBProjectInfoTimeOperationCompleted);
            }
            this.InvokeAsync("TBProjectInfoTime", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.TBProjectInfoTimeOperationCompleted, userState);
        }
        
        private void OnTBProjectInfoTimeOperationCompleted(object arg) {
            if ((this.TBProjectInfoTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TBProjectInfoTimeCompleted(this, new TBProjectInfoTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string RetrieveData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in6) {
            object[] results = this.Invoke("RetrieveData", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveDataAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6) {
            this.RetrieveDataAsync(in0, in1, in2, in3, in4, in5, in6, null);
        }
        
        /// <remarks/>
        public void RetrieveDataAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6, object userState) {
            if ((this.RetrieveDataOperationCompleted == null)) {
                this.RetrieveDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveDataOperationCompleted);
            }
            this.InvokeAsync("RetrieveData", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6}, this.RetrieveDataOperationCompleted, userState);
        }
        
        private void OnRetrieveDataOperationCompleted(object arg) {
            if ((this.RetrieveDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveDataCompleted(this, new RetrieveDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string TBContractRecordManageTime([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4) {
            object[] results = this.Invoke("TBContractRecordManageTime", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TBContractRecordManageTimeAsync(string in0, string in1, string in2, string in3, string in4) {
            this.TBContractRecordManageTimeAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void TBContractRecordManageTimeAsync(string in0, string in1, string in2, string in3, string in4, object userState) {
            if ((this.TBContractRecordManageTimeOperationCompleted == null)) {
                this.TBContractRecordManageTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTBContractRecordManageTimeOperationCompleted);
            }
            this.InvokeAsync("TBContractRecordManageTime", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.TBContractRecordManageTimeOperationCompleted, userState);
        }
        
        private void OnTBContractRecordManageTimeOperationCompleted(object arg) {
            if ((this.TBContractRecordManageTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TBContractRecordManageTimeCompleted(this, new TBContractRecordManageTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string SnapDataByInternet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("SnapDataByInternet", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SnapDataByInternetAsync(string in0, string in1, string in2, string in3) {
            this.SnapDataByInternetAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void SnapDataByInternetAsync(string in0, string in1, string in2, string in3, object userState) {
            if ((this.SnapDataByInternetOperationCompleted == null)) {
                this.SnapDataByInternetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSnapDataByInternetOperationCompleted);
            }
            this.InvokeAsync("SnapDataByInternet", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.SnapDataByInternetOperationCompleted, userState);
        }
        
        private void OnSnapDataByInternetOperationCompleted(object arg) {
            if ((this.SnapDataByInternetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SnapDataByInternetCompleted(this, new SnapDataByInternetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string Huoqu([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("Huoqu", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HuoquAsync(string in0) {
            this.HuoquAsync(in0, null);
        }
        
        /// <remarks/>
        public void HuoquAsync(string in0, object userState) {
            if ((this.HuoquOperationCompleted == null)) {
                this.HuoquOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHuoquOperationCompleted);
            }
            this.InvokeAsync("Huoqu", new object[] {
                        in0}, this.HuoquOperationCompleted, userState);
        }
        
        private void OnHuoquOperationCompleted(object arg) {
            if ((this.HuoquCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HuoquCompleted(this, new HuoquCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string SaveTBDataToSt([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("SaveTBDataToSt", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveTBDataToStAsync(string in0, string in1, string in2, string in3) {
            this.SaveTBDataToStAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void SaveTBDataToStAsync(string in0, string in1, string in2, string in3, object userState) {
            if ((this.SaveTBDataToStOperationCompleted == null)) {
                this.SaveTBDataToStOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveTBDataToStOperationCompleted);
            }
            this.InvokeAsync("SaveTBDataToSt", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.SaveTBDataToStOperationCompleted, userState);
        }
        
        private void OnSaveTBDataToStOperationCompleted(object arg) {
            if ((this.SaveTBDataToStCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveTBDataToStCompleted(this, new SaveTBDataToStCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string HTBA([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("HTBA", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HTBAAsync(string in0, string in1, string in2) {
            this.HTBAAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void HTBAAsync(string in0, string in1, string in2, object userState) {
            if ((this.HTBAOperationCompleted == null)) {
                this.HTBAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHTBAOperationCompleted);
            }
            this.InvokeAsync("HTBA", new object[] {
                        in0,
                        in1,
                        in2}, this.HTBAOperationCompleted, userState);
        }
        
        private void OnHTBAOperationCompleted(object arg) {
            if ((this.HTBACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HTBACompleted(this, new HTBACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getXyptPjfmx([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("getXyptPjfmx", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getXyptPjfmxAsync(string in0, string in1, string in2) {
            this.getXyptPjfmxAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void getXyptPjfmxAsync(string in0, string in1, string in2, object userState) {
            if ((this.getXyptPjfmxOperationCompleted == null)) {
                this.getXyptPjfmxOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXyptPjfmxOperationCompleted);
            }
            this.InvokeAsync("getXyptPjfmx", new object[] {
                        in0,
                        in1,
                        in2}, this.getXyptPjfmxOperationCompleted, userState);
        }
        
        private void OngetXyptPjfmxOperationCompleted(object arg) {
            if ((this.getXyptPjfmxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXyptPjfmxCompleted(this, new getXyptPjfmxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string saveZcjzs([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in5) {
            object[] results = this.Invoke("saveZcjzs", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveZcjzsAsync(string in0, string in1, byte[] in2, string in3, string in4, string in5) {
            this.saveZcjzsAsync(in0, in1, in2, in3, in4, in5, null);
        }
        
        /// <remarks/>
        public void saveZcjzsAsync(string in0, string in1, byte[] in2, string in3, string in4, string in5, object userState) {
            if ((this.saveZcjzsOperationCompleted == null)) {
                this.saveZcjzsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveZcjzsOperationCompleted);
            }
            this.InvokeAsync("saveZcjzs", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5}, this.saveZcjzsOperationCompleted, userState);
        }
        
        private void OnsaveZcjzsOperationCompleted(object arg) {
            if ((this.saveZcjzsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveZcjzsCompleted(this, new saveZcjzsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string TBProjectInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4) {
            object[] results = this.Invoke("TBProjectInfo", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TBProjectInfoAsync(string in0, string in1, string in2, string in3, string in4) {
            this.TBProjectInfoAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void TBProjectInfoAsync(string in0, string in1, string in2, string in3, string in4, object userState) {
            if ((this.TBProjectInfoOperationCompleted == null)) {
                this.TBProjectInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTBProjectInfoOperationCompleted);
            }
            this.InvokeAsync("TBProjectInfo", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.TBProjectInfoOperationCompleted, userState);
        }
        
        private void OnTBProjectInfoOperationCompleted(object arg) {
            if ((this.TBProjectInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TBProjectInfoCompleted(this, new TBProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getQsXyptPjf([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("getQsXyptPjf", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getQsXyptPjfAsync(string in0, string in1, string in2) {
            this.getQsXyptPjfAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void getQsXyptPjfAsync(string in0, string in1, string in2, object userState) {
            if ((this.getQsXyptPjfOperationCompleted == null)) {
                this.getQsXyptPjfOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetQsXyptPjfOperationCompleted);
            }
            this.InvokeAsync("getQsXyptPjf", new object[] {
                        in0,
                        in1,
                        in2}, this.getQsXyptPjfOperationCompleted, userState);
        }
        
        private void OngetQsXyptPjfOperationCompleted(object arg) {
            if ((this.getQsXyptPjfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getQsXyptPjfCompleted(this, new getQsXyptPjfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string TjxtFromXmData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("TjxtFromXmData", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TjxtFromXmDataAsync(string in0, string in1, string in2, string in3) {
            this.TjxtFromXmDataAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void TjxtFromXmDataAsync(string in0, string in1, string in2, string in3, object userState) {
            if ((this.TjxtFromXmDataOperationCompleted == null)) {
                this.TjxtFromXmDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTjxtFromXmDataOperationCompleted);
            }
            this.InvokeAsync("TjxtFromXmData", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.TjxtFromXmDataOperationCompleted, userState);
        }
        
        private void OnTjxtFromXmDataOperationCompleted(object arg) {
            if ((this.TjxtFromXmDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TjxtFromXmDataCompleted(this, new TjxtFromXmDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string SaveDataToSt([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4) {
            object[] results = this.Invoke("SaveDataToSt", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveDataToStAsync(string in0, string in1, string in2, string in3, string in4) {
            this.SaveDataToStAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void SaveDataToStAsync(string in0, string in1, string in2, string in3, string in4, object userState) {
            if ((this.SaveDataToStOperationCompleted == null)) {
                this.SaveDataToStOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveDataToStOperationCompleted);
            }
            this.InvokeAsync("SaveDataToSt", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.SaveDataToStOperationCompleted, userState);
        }
        
        private void OnSaveDataToStOperationCompleted(object arg) {
            if ((this.SaveDataToStCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveDataToStCompleted(this, new SaveDataToStCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string SaveStData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4) {
            object[] results = this.Invoke("SaveStData", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveStDataAsync(string in0, string in1, string in2, string in3, string in4) {
            this.SaveStDataAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void SaveStDataAsync(string in0, string in1, string in2, string in3, string in4, object userState) {
            if ((this.SaveStDataOperationCompleted == null)) {
                this.SaveStDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveStDataOperationCompleted);
            }
            this.InvokeAsync("SaveStData", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.SaveStDataOperationCompleted, userState);
        }
        
        private void OnSaveStDataOperationCompleted(object arg) {
            if ((this.SaveStDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveStDataCompleted(this, new SaveStDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string TjxtFromQyData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("TjxtFromQyData", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TjxtFromQyDataAsync(string in0, string in1, string in2) {
            this.TjxtFromQyDataAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void TjxtFromQyDataAsync(string in0, string in1, string in2, object userState) {
            if ((this.TjxtFromQyDataOperationCompleted == null)) {
                this.TjxtFromQyDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTjxtFromQyDataOperationCompleted);
            }
            this.InvokeAsync("TjxtFromQyData", new object[] {
                        in0,
                        in1,
                        in2}, this.TjxtFromQyDataOperationCompleted, userState);
        }
        
        private void OnTjxtFromQyDataOperationCompleted(object arg) {
            if ((this.TjxtFromQyDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TjxtFromQyDataCompleted(this, new TjxtFromQyDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Server.WebService", ResponseNamespace="http://Server.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string ToCityPlatform([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("ToCityPlatform", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ToCityPlatformAsync(string in0, string in1, string in2) {
            this.ToCityPlatformAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void ToCityPlatformAsync(string in0, string in1, string in2, object userState) {
            if ((this.ToCityPlatformOperationCompleted == null)) {
                this.ToCityPlatformOperationCompleted = new System.Threading.SendOrPostCallback(this.OnToCityPlatformOperationCompleted);
            }
            this.InvokeAsync("ToCityPlatform", new object[] {
                        in0,
                        in1,
                        in2}, this.ToCityPlatformOperationCompleted, userState);
        }
        
        private void OnToCityPlatformOperationCompleted(object arg) {
            if ((this.ToCityPlatformCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ToCityPlatformCompleted(this, new ToCityPlatformCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.8009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Server.WebService")]
    public partial class anyType2anyTypeMapEntry {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        public object key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void getGdxyfCompletedEventHandler(object sender, getGdxyfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGdxyfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGdxyfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void TBContractRecordManageCompletedEventHandler(object sender, TBContractRecordManageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TBContractRecordManageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TBContractRecordManageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void GetDataFromSxyptCompletedEventHandler(object sender, GetDataFromSxyptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataFromSxyptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataFromSxyptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void getXyptPjfCompletedEventHandler(object sender, getXyptPjfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXyptPjfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXyptPjfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void SendBeginCompletedEventHandler(object sender, SendBeginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBeginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBeginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public anyType2anyTypeMapEntry[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((anyType2anyTypeMapEntry[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void ReceiveDataCompletedEventHandler(object sender, ReceiveDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void SnapFileByInternetCompletedEventHandler(object sender, SnapFileByInternetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SnapFileByInternetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SnapFileByInternetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void getXyptRsCompletedEventHandler(object sender, getXyptRsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXyptRsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXyptRsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void TjRetrieveByUpdateCompletedEventHandler(object sender, TjRetrieveByUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TjRetrieveByUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TjRetrieveByUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void XyInnerptPjfCompletedEventHandler(object sender, XyInnerptPjfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XyInnerptPjfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XyInnerptPjfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void TBProjectInfoTimeCompletedEventHandler(object sender, TBProjectInfoTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TBProjectInfoTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TBProjectInfoTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void RetrieveDataCompletedEventHandler(object sender, RetrieveDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void TBContractRecordManageTimeCompletedEventHandler(object sender, TBContractRecordManageTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TBContractRecordManageTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TBContractRecordManageTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void SnapDataByInternetCompletedEventHandler(object sender, SnapDataByInternetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SnapDataByInternetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SnapDataByInternetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void HuoquCompletedEventHandler(object sender, HuoquCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HuoquCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HuoquCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void SaveTBDataToStCompletedEventHandler(object sender, SaveTBDataToStCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveTBDataToStCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveTBDataToStCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void HTBACompletedEventHandler(object sender, HTBACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HTBACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HTBACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void getXyptPjfmxCompletedEventHandler(object sender, getXyptPjfmxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXyptPjfmxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXyptPjfmxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void saveZcjzsCompletedEventHandler(object sender, saveZcjzsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveZcjzsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveZcjzsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void TBProjectInfoCompletedEventHandler(object sender, TBProjectInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TBProjectInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TBProjectInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void getQsXyptPjfCompletedEventHandler(object sender, getQsXyptPjfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getQsXyptPjfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getQsXyptPjfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void TjxtFromXmDataCompletedEventHandler(object sender, TjxtFromXmDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TjxtFromXmDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TjxtFromXmDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void SaveDataToStCompletedEventHandler(object sender, SaveDataToStCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveDataToStCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveDataToStCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void SaveStDataCompletedEventHandler(object sender, SaveStDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveStDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveStDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void TjxtFromQyDataCompletedEventHandler(object sender, TjxtFromQyDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TjxtFromQyDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TjxtFromQyDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    public delegate void ToCityPlatformCompletedEventHandler(object sender, ToCityPlatformCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.7905")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ToCityPlatformCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ToCityPlatformCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591