//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WxjzgcjczyTimerService.DataShareServiceSpace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataShareServiceSpace.DataShareServiceSoap")]
    public interface DataShareServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShareDataXML", ReplyAction="*")]
        WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLResponse ShareDataXML(WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShareDataXML2", ReplyAction="*")]
        WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2Response ShareDataXML2(WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2Request request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTatalPageNum", ReplyAction="*")]
        WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumResponse GetTatalPageNum(WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShareDataXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShareDataXML", Namespace="http://tempuri.org/", Order=0)]
        public WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLRequestBody Body;
        
        public ShareDataXMLRequest() {
        }
        
        public ShareDataXMLRequest(WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShareDataXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endDate;
        
        public ShareDataXMLRequestBody() {
        }
        
        public ShareDataXMLRequestBody(string userid, string password, System.DateTime startDate, System.DateTime endDate) {
            this.userid = userid;
            this.password = password;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShareDataXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShareDataXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLResponseBody Body;
        
        public ShareDataXMLResponse() {
        }
        
        public ShareDataXMLResponse(WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShareDataXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShareDataXMLResult;
        
        public ShareDataXMLResponseBody() {
        }
        
        public ShareDataXMLResponseBody(string ShareDataXMLResult) {
            this.ShareDataXMLResult = ShareDataXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShareDataXML2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShareDataXML2", Namespace="http://tempuri.org/", Order=0)]
        public WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2RequestBody Body;
        
        public ShareDataXML2Request() {
        }
        
        public ShareDataXML2Request(WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShareDataXML2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int DataContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int CurrentPageNum;
        
        public ShareDataXML2RequestBody() {
        }
        
        public ShareDataXML2RequestBody(string userid, string password, System.DateTime startDate, System.DateTime endDate, int DataContent, int CurrentPageNum) {
            this.userid = userid;
            this.password = password;
            this.startDate = startDate;
            this.endDate = endDate;
            this.DataContent = DataContent;
            this.CurrentPageNum = CurrentPageNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShareDataXML2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShareDataXML2Response", Namespace="http://tempuri.org/", Order=0)]
        public WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2ResponseBody Body;
        
        public ShareDataXML2Response() {
        }
        
        public ShareDataXML2Response(WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShareDataXML2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShareDataXML2Result;
        
        public ShareDataXML2ResponseBody() {
        }
        
        public ShareDataXML2ResponseBody(string ShareDataXML2Result) {
            this.ShareDataXML2Result = ShareDataXML2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTatalPageNumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTatalPageNum", Namespace="http://tempuri.org/", Order=0)]
        public WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumRequestBody Body;
        
        public GetTatalPageNumRequest() {
        }
        
        public GetTatalPageNumRequest(WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTatalPageNumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int DataContent;
        
        public GetTatalPageNumRequestBody() {
        }
        
        public GetTatalPageNumRequestBody(string userid, string password, System.DateTime startDate, System.DateTime endDate, int DataContent) {
            this.userid = userid;
            this.password = password;
            this.startDate = startDate;
            this.endDate = endDate;
            this.DataContent = DataContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTatalPageNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTatalPageNumResponse", Namespace="http://tempuri.org/", Order=0)]
        public WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumResponseBody Body;
        
        public GetTatalPageNumResponse() {
        }
        
        public GetTatalPageNumResponse(WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTatalPageNumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetTatalPageNumResult;
        
        public GetTatalPageNumResponseBody() {
        }
        
        public GetTatalPageNumResponseBody(int GetTatalPageNumResult) {
            this.GetTatalPageNumResult = GetTatalPageNumResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataShareServiceSoapChannel : WxjzgcjczyTimerService.DataShareServiceSpace.DataShareServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataShareServiceSoapClient : System.ServiceModel.ClientBase<WxjzgcjczyTimerService.DataShareServiceSpace.DataShareServiceSoap>, WxjzgcjczyTimerService.DataShareServiceSpace.DataShareServiceSoap {
        
        public DataShareServiceSoapClient() {
        }
        
        public DataShareServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataShareServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataShareServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataShareServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLResponse WxjzgcjczyTimerService.DataShareServiceSpace.DataShareServiceSoap.ShareDataXML(WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLRequest request) {
            return base.Channel.ShareDataXML(request);
        }
        
        public string ShareDataXML(string userid, string password, System.DateTime startDate, System.DateTime endDate) {
            WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLRequest inValue = new WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLRequest();
            inValue.Body = new WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.password = password;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXMLResponse retVal = ((WxjzgcjczyTimerService.DataShareServiceSpace.DataShareServiceSoap)(this)).ShareDataXML(inValue);
            return retVal.Body.ShareDataXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2Response WxjzgcjczyTimerService.DataShareServiceSpace.DataShareServiceSoap.ShareDataXML2(WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2Request request) {
            return base.Channel.ShareDataXML2(request);
        }
        
        public string ShareDataXML2(string userid, string password, System.DateTime startDate, System.DateTime endDate, int DataContent, int CurrentPageNum) {
            WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2Request inValue = new WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2Request();
            inValue.Body = new WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2RequestBody();
            inValue.Body.userid = userid;
            inValue.Body.password = password;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            inValue.Body.DataContent = DataContent;
            inValue.Body.CurrentPageNum = CurrentPageNum;
            WxjzgcjczyTimerService.DataShareServiceSpace.ShareDataXML2Response retVal = ((WxjzgcjczyTimerService.DataShareServiceSpace.DataShareServiceSoap)(this)).ShareDataXML2(inValue);
            return retVal.Body.ShareDataXML2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumResponse WxjzgcjczyTimerService.DataShareServiceSpace.DataShareServiceSoap.GetTatalPageNum(WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumRequest request) {
            return base.Channel.GetTatalPageNum(request);
        }
        
        public int GetTatalPageNum(string userid, string password, System.DateTime startDate, System.DateTime endDate, int DataContent) {
            WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumRequest inValue = new WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumRequest();
            inValue.Body = new WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.password = password;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            inValue.Body.DataContent = DataContent;
            WxjzgcjczyTimerService.DataShareServiceSpace.GetTatalPageNumResponse retVal = ((WxjzgcjczyTimerService.DataShareServiceSpace.DataShareServiceSoap)(this)).GetTatalPageNum(inValue);
            return retVal.Body.GetTatalPageNumResult;
        }
    }
}
