<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="LeftFrame.aspx.cs" Inherits="Bigdesk8.Business.LeftFrame" %>

<html>
<head runat="server">
    <title>左侧框架</title>
    <link href="Styles/frame.css" rel="stylesheet" type="text/css" />
</head>
<body style="background: url(Images/FrameImages/LeftFrame_Bk.jpg) no-repeat;">
    <form id="form1" runat="server">
    <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td width="5px">
            </td>
            <td>
                <asp:TreeView ID="TreeView1" runat="server" AutoGenerateDataBindings="False" ExpandDepth="1"
                    NodeIndent="10" ShowExpandCollapse="False" OnSelectedNodeChanged="TreeView1_SelectedNodeChanged">
                    <Nodes>
                        <asp:TreeNode ImageUrl="Images/1.jpg" ImageToolTip="用户权限管理" Text="" Value="用户权限管理"
                            Expanded="false">
                            <asp:TreeNode ImageUrl="Images/1.jpg" NavigateUrl="UserRightManager/UserInfo/UserList.aspx"
                                Target="rightFrame" ImageToolTip="用户管理" Text="" Value="用户管理"></asp:TreeNode>
                            <asp:TreeNode ImageUrl="Images/1.jpg" NavigateUrl="UserRightManager/UserAttribute/AttributeList.aspx"
                                Target="rightFrame" ImageToolTip="特性管理" Text="" Value="特性管理"></asp:TreeNode>
                            <asp:TreeNode ImageUrl="Images/1.jpg" NavigateUrl="UserRightManager/UserAttribute/UserAttributeList.aspx"
                                Target="rightFrame" ImageToolTip="用户特性" Text="" Value="用户特性"></asp:TreeNode>
                            <asp:TreeNode ImageUrl="Images/1.jpg" NavigateUrl="UserRightManager/UserRole/RoleList.aspx"
                                Target="rightFrame" ImageToolTip="角色管理" Text="" Value="角色管理"></asp:TreeNode>
                            <asp:TreeNode ImageUrl="Images/1.jpg" NavigateUrl="UserRightManager/UserRole/UserRoleList.aspx"
                                Target="rightFrame" ImageToolTip="用户角色" Text="" Value="用户角色"></asp:TreeNode>
                            <asp:TreeNode ImageUrl="Images/1.jpg" NavigateUrl="UserRightManager/RoleRight/RoleRightList.aspx"
                                Target="rightFrame" ImageToolTip="角色权限" Text="" Value="角色权限"></asp:TreeNode>
                        </asp:TreeNode>
                        <asp:TreeNode ImageUrl="Images/1.jpg" NavigateUrl="FileManager/List.aspx" Target="rightFrame"
                            ImageToolTip="文件管理" Text="" Value="文件管理"></asp:TreeNode>
                        <asp:TreeNode ImageUrl="Images/1.jpg" NavigateUrl="LogManager/List.aspx" Target="rightFrame"
                            ImageToolTip="系统日志" Text="" Value="系统日志"></asp:TreeNode>
                        <asp:TreeNode ImageUrl="Images/1.jpg" NavigateUrl="DebugManager/List.aspx" Target="rightFrame"
                            ImageToolTip="调试跟踪" Text="" Value="调试跟踪"></asp:TreeNode>
                        <asp:TreeNode ImageUrl="Images/1.jpg" NavigateUrl="CacheManager/ClearCache.aspx"
                            Target="rightFrame" ImageToolTip="清除缓存" Text="" Value="清除缓存"></asp:TreeNode>
                    </Nodes>
                </asp:TreeView>
            </td>
            <td width="14px">
            </td>
        </tr>
    </table>
    </form>
</body>
</html>
