//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.17929 版自动生成。
// 
#pragma warning disable 1591

namespace WxjzgcjczyTimerService.WebServiceStxm {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceStxmSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceStxm : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadStxmOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadStxmByStStandardOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceStxm() {
            this.Url = global::WxjzgcjczyTimerService.Properties.Settings.Default.WxjzgcjczyTimerService3_0_WebServiceStxm_WebServiceStxm;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadStxmCompletedEventHandler ReadStxmCompleted;
        
        /// <remarks/>
        public event ReadStxmByStStandardCompletedEventHandler ReadStxmByStStandardCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReadStxm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReadStxm(string userName, string password, string zzjgdm) {
            object[] results = this.Invoke("ReadStxm", new object[] {
                        userName,
                        password,
                        zzjgdm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReadStxmAsync(string userName, string password, string zzjgdm) {
            this.ReadStxmAsync(userName, password, zzjgdm, null);
        }
        
        /// <remarks/>
        public void ReadStxmAsync(string userName, string password, string zzjgdm, object userState) {
            if ((this.ReadStxmOperationCompleted == null)) {
                this.ReadStxmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadStxmOperationCompleted);
            }
            this.InvokeAsync("ReadStxm", new object[] {
                        userName,
                        password,
                        zzjgdm}, this.ReadStxmOperationCompleted, userState);
        }
        
        private void OnReadStxmOperationCompleted(object arg) {
            if ((this.ReadStxmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadStxmCompleted(this, new ReadStxmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReadStxmByStStandard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReadStxmByStStandard(string userName, string password, string zzjgdm, string ssqx, string sscs) {
            object[] results = this.Invoke("ReadStxmByStStandard", new object[] {
                        userName,
                        password,
                        zzjgdm,
                        ssqx,
                        sscs});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReadStxmByStStandardAsync(string userName, string password, string zzjgdm, string ssqx, string sscs) {
            this.ReadStxmByStStandardAsync(userName, password, zzjgdm, ssqx, sscs, null);
        }
        
        /// <remarks/>
        public void ReadStxmByStStandardAsync(string userName, string password, string zzjgdm, string ssqx, string sscs, object userState) {
            if ((this.ReadStxmByStStandardOperationCompleted == null)) {
                this.ReadStxmByStStandardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadStxmByStStandardOperationCompleted);
            }
            this.InvokeAsync("ReadStxmByStStandard", new object[] {
                        userName,
                        password,
                        zzjgdm,
                        ssqx,
                        sscs}, this.ReadStxmByStStandardOperationCompleted, userState);
        }
        
        private void OnReadStxmByStStandardOperationCompleted(object arg) {
            if ((this.ReadStxmByStStandardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadStxmByStStandardCompleted(this, new ReadStxmByStStandardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReadStxmCompletedEventHandler(object sender, ReadStxmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadStxmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadStxmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReadStxmByStStandardCompletedEventHandler(object sender, ReadStxmByStStandardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadStxmByStStandardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadStxmByStStandardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591